learning_rate: .01
num_epochs: 1000
device: cpu
dtype: constants.DTYPE
train_val_ratio: .1
evaluation_interval: 1
epoch_blocks: 1
nrep: 10
dedpul_type: dedpul
dataset_kind: LPU
cv: 5
estimate_diff_options:
    MT: true, 
    MT_coef: 0.25
    decay_MT_coef: false
    tune: false
    bw_mix: 0.05 
    bw_pos: 0.1 
    threshold: mid
    n_gauss_mix: 20
    n_gauss_pos: 10
    bins_mix: 20
    bins_pos: 20 
    k_neighbours: null
batch_size: 
  train: 64
  test: null
  val: null
  holdout: null
ratios: 
  # *** NOTE ***
  # TRAIN_RATIO == 1. - HOLDOUT_RATIO - TEST_RATIO - VAL_RATIO
  # i.e. test_ratio + val_ratio + holdout_ratio + train_ratio == 1
  test: 0.25 
  val: 0.2
  holdout: .05 
  train: .5 
train_nn_options:  
  loss_function: log
  n_early_stop: 20
  disp: false
