device: cpu
dataset: null #fmnist
datapath: null #data/FMNIST_data
num_labeled: null #10000
num_workers: 1
loss: Dist-PU
warm_up_lr: 0.001
lr: .001
warm_up_weight_decay: 0.005
weight_decay: 0.001
optimizer: adam
schedular: cos-ann
entropy: 1
co_mu: 0.002
co_entropy: 0.004
alpha: 6.0
co_mix_entropy: 0.04
co_mixup: 5.0
warm_up_epochs: 100
pu_epochs: 500
random_seed: 0
ratios: 
  # *** NOTE ***
  # TRAIN_RATIO == 1. - HOLDOUT_RATIO - TEST_RATIO - VAL_RATIO
  # i.e. test_ratio + val_ratio + holdout_ratio + train_ratio == 1
  test: 0.05
  val: 0.4
  holdout: 0.05
  train: .5
dataset_kind: LPU
batch_size: 
  train: 64
  test: 64
  val: 64
  holdout: 64


 