lr: 0.01
wd: 0.0005
momentum: 0.9
data_type: None
train_method: TEDn
net_type: LeNet
sigmoid_loss: true
estimate_alpha: true
warm_start: true
warm_start_epochs: 100
epochs: 100
alpha: 0.5
beta: 0.5
log_dir: logging_accuracy
data_dir: data
optimizer: Adam
alpha_estimate: 0.0
show_bar: false
use_alpha: false
device: cpu
dataset_kind: LPU
ratios: 
  # *** NOTE ***
  # TRAIN_RATIO == 1. - HOLDOUT_RATIO - TEST_RATIO - VAL_RATIO
  # i.e. test_ratio + val_ratio + holdout_ratio + train_ratio == 1
  test: 0.25 
  val: 0.2
  holdout: .05 
  train: .5 
batch_size: 
  train: 64
  test: 64
  val: 64
  holdout: 64
data_generating_process: SB #SB # either of CC (case-control) or (SB) (selection-bias)

