device: cpu
dataset_name:  animal_no_animal #fashionMNIST
dataset_kind: LPU
gpu: 9
val_iterations: 30
num_labeled: 3000
learning_rate: 0.001
epochs: 50
mix_alpha: 0.3
data_generating_process: CC #SB # either of CC (case-control) or (SB) (selection-bias)
lam: 0.3
# positive_label_list: [1, 4, 7]
random_seed: 0
ratios: 
  # *** NOTE ***
  # TRAIN_RATIO : :  1. - HOLDOUT_RATIO - TEST_RATIO - VAL_RATIO
  # i.e. test_ratio + val_ratio + holdout_ratio + train_ratio : :  1
  test: 0.05
  val: 0.4
  holdout: 0.05
  train: .5
batch_size: 
  train: 64
  test: 64
  val: 64
  holdout: 64

  # train: 500
  # test: 500
  # val: 500
  # holdout: 500

 