lr: 0.001
wd: 0.0005
momentum: 0.9
batch_size: 64
data_type: mnist_17
train_method: TEDn
net_type: LeNet
sigmoid_loss: true
estimate_alpha: true
warm_start: true
warm_start_epochs: 50
epochs: 200
seed: 42
alpha: 0.5
beta: 0.5
log_dir: logging_accuracy
data_dir: data
optimizer: Adam
alpha_estimate: 0.0
show_bar: false
use_alpha: false
device: cpu
dataset_kind: LPU
ratios: 
  # *** NOTE ***
  # TRAIN_RATIO == 1. - HOLDOUT_RATIO - TEST_RATIO - VAL_RATIO
  # i.e. test_ratio + val_ratio + holdout_ratio + train_ratio == 1
  test: 0.35 
  val: 0.1 
  holdout: .05 
  train: .5 
